#!/bin/bash

BRANCH=`git rev-parse --abbrev-ref HEAD`
echo "on branch $BRANCH"

set -e

if [[ $BRANCH == "master" ]];
then
  pnpm lerna publish --yes --conventional-graduate=@react95/gatsby-theme
elif [[ $BRANCH == "alpha" ]];
then
  pnpm lerna publish --conventional-prerelease --yes --preid $BRANCH --dist-tag $BRANCH
else
  echo "Nothing to publish on branch $BRANCH..."
fi
